### ISSUE TITLE
Getting TypeError

### ISSUE THREAD

**Issue by williamlynngray** [jonathanbow/airtable-find-and-replace#2]
Getting this error running the verbatim script in Airtable today:

"TypeError: null is not an object (evaluating 'record.getCellValue(field.name).includes')

asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]"

**Comment by williamlynngray** [comment]
// Copy/pasting in code to validate:



// user chooses the table...
let table = await input.tableAsync('Pick a table');
// ...and a field
let field = await input.fieldAsync("Pick a field", table);
// Shows the field name and field type
output.text(`Field "${field.name}" has type "${field.type}".`);

// The script only works against text-type fields
if(field.type == 'singleLineText' || field.type == 'multilineText' || field.type == 'richText') {
    // enter the string you want to find...
    let stringToFind = await input.textAsync('Enter the string to find');
    // ...and the string you want to replace it with
    let stringToReplace = await input.textAsync('Enter the string to replace it with');
    // define a new regex based on the sting to find
    // this configuration replaces all instances of the string to find and is case sensitive
    let myRegex = new RegExp(stringToFind,"g");
    // get the records from the table
    let query = await table.selectRecordsAsync();
    let countOfRecords = 0;
    output.text("The following records will be changed:")
    // get the records which contain the string to find and output the before and after version
    // note that records are not changed at this point, we're just showing what will be changed if you go ahead
    for (let record of query.records) {
        if (record.getCellValue(field.name).includes(stringToFind)) {
            let newText = record.getCellValue(field.name).replace(myRegex, stringToReplace);
            output.text(`(Record: ${record.name}) ${record.getCellValue(field.name)} => ${newText}`);
            output.text("============================");
            countOfRecords = countOfRecords += 1;
        }
    }
    // if nothing matches the string to find, then finish
    if (countOfRecords == 0) {
        output.text("Sorry - can't find any records to update - please try again!")
    } else if (countOfRecords > 0) {
        // otherwise check with the user if they want to proceed with the find and replace
        let proceedOrCancel = await input.buttonsAsync('Would you like to proceed or cancel?', ['Proceed', 'Cancel']);
        if (proceedOrCancel === 'Proceed') {
            output.text('Proceeding...');
            for (let record of query.records) {
                if (record.getCellValue(field.name).includes(stringToFind)) {
                    let newText = record.getCellValue(field.name).replace(myRegex, stringToReplace);
                    // update the records
                    let update = table.updateRecordAsync(record, {
                        [field.name]: newText
                    })
                    output.text(`Record: ${record.name} updated`);
                }
            }
            output.text("The find and replace action has finished")
        } else {
            output.text("The find and replace action was cancelled");
        }
    }
} else {
    // if field type is not a text type field then let the user know
    output.text(`Sorry - can't do find & replace on a ${field.type} field`);
}

**Comment by williamlynngray** [comment]
Got above error when running the script in Safari 13.1.  

I get this error instead with Chrome (ac) 80.0.3987.149:

TypeError: Cannot read property 'includes' of null
    at main on line 44

**Comment by williamlynngray** [comment]
Just tested the newly-committed version (23 days ago) and it works flawlessly, thanks.

**Comment by jonathanbow** [comment]
Closing issue as all resolved
